baseURL: "https://retalone.github.io"
languageCode: "en-us"
title: "Portfolio de William"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: AP et Projets
      title: Ap et Projets
      url: /projets/
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages/
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio de William"
  description: Un portfolio parmis tant d'autres
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME" 
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: justify # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Made by RetalOne's Corporation" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Salut, je suis"
    title: "William."
    subtitle: "Un élève de SIO"
    content: "Spécialité réseaux"
    image: /images/Profil.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Résumé"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RetalOne
        - icon: fab fa-x-twitter
          url: https://x.com/OneRetal
      customIcons:
        - icon: /instagram.jfif
          url: "https://instagram.com/retaloneofficial"

  # About
  about:
    enable: true
    title: "A propos de moi"
    image: "/images/Profil.jpg"
    content: |-
      Titulaire d'un baccalauréat général et de la certification PIX, et ayant suivi les spécialités Physique-Chimie et SVT ainsi que la section européenne l'année 2021- 2022, je m'intéresse à l'informatique depuis 2020. Cet intérêt venant en grande partie du confinement lié au Covid-19. J'ai développé une passion pour l'informatique, principalement l'hardware. Je suis une formation en BTS SIO (Brevet de Technicien Supérieur Service Informatique aux Organisations. J'aspire à devenir technicien informatique ou administrateur système.
    skills:
      enable: true
      title: "Systèmes et logiciels avec lesquels je suis à l'aise:"
      items:
        - "Windows Server"
        - "ESXi"
        - "WAPT"
        - "HYPER-V"
        - "QEMU-IMG"
        - "Hyperius Backup"
        - "Truenas"

  # Experience
  experience:
    enable: true
    title: "Expériences professionnelles"
    items:
      - job: "Stagiaire à l'EPLEFPA Edgard PISANI"
        company: "EPLEFPA Edgard PISANI"
        date: "Juin 2023 et du 15 Janvier - 17 février 2024"
        featuredLink:
          enable: true
          name: "EPLEFPA Edgard PISANI"
          url: "https://edgard-pisani.educagri.fr"
        info:
          enable: true
          content: "Stagiaire"
        content: "J'ai effectué mon stage de première et deuxième année de SIO à l'EPLEFPA Edgard Pisani de Chaumont pour une durée de 5 semaines. J'ai pu découvrir le métier d'administrateur réseau plus en profondeur,
             renforcer des aquis tout en augmentant la liste de ceux-ci."

      - job: "Stagiaire chez Termoforma"
        company: "Termoforma"
        date: "2019"
        featuredLink:
          enable: true
          name: "Termoforma"
          url: "https://termoforma-france.com"
        info:
          enable: true
          content: Stagiaire
        content: |
          J'ai effectué mon stage de troisième dans l'entreprise de fabrication de pièces de motos Termoforma durant une semaine. J'ai pu participer à la création d'une pièce, de son moulage à sa découpe jusqu'à emballage final.
          J'ai pu ainsi voir et comprendre toutes les étapes de fabrication des différentes pièces.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Baccalauréat général (Première et terminale)"
        school:
          name: "Lycée Georges Colomb"
          url: "https://www.lyc-colomb.ac-besancon.fr"
        date: "Septembre 2020 - Juin 2022"
        content: |-
          Options
          - Physique-Chimie jusqu'en terminale
          - SVT jusqu'en terminale
          - Mathématiques jusqu'en première
          - Option Euro-Anglais jusqu'en terminale

          Résultat du baccalauréat
            - Baccalauréat obtenu sans mention.
        #featuredLink:
          #enable: true
          #name: "My academic record"
          #url: "https://example.com"

      - title: "Baccalauréat général (seconde)"
        school:
          name: "Lycée Charles de Gaulle"
          url: "https://www.lyceecdg52.com/"
        date: "Septembre 2019 - Juin 2020"
        content: |-
          Options
          - Euro Anglais
          - Sciences de l'ingénieur
        #featuredLink:
          #enable: true
          #url: "https://example.com"

      - title: "Brevet"
        school:
          name: "Collège la Rochotte"
          url: "https://clg-la-rochotte.monbureaunumerique.fr/"
        date: "Septembre 2015 - Juin 2019"
        content: |-
          Diplôme obtenu
          - Brevet des collèges, mention très bien.


  # Achievements
  achievements:
    enable: true
    title: "Diplômes"
    items:
      - title: Brevet des Collèges
        content: Obtention du Brevet des Collèges avec mention très bien
        #url: https://example.com
        #image: /images/achievment.jpg
      - title: Baccalauréat Général
        content: Obtention du Baccalauréat Général options Physique-Chimie/SVT sans mention
        #image: /images/achievment.jpg
      #- title: Hugo Profile
        #content: Developed a theme and getting 1K+ downloads per month.
        #url: "https://github.com/gurusabarish/hugo-profile"
        #image: /images/achievment.jpg
      #- title: Microsoft Imagine Runner
        #content: We are developed a product which can help others.
      #- title: Google Summer of Code
        #content: Contributed to a open source project.
        #url: https://example.com

  # projects
  projects:
    enable: true
    title: "Projets"
    items:
      - title: Portfolio avec HUGO
        content: Le portfolio que vous êtes en train de lire.
        image: /images/projects/Page1.PNG
        links:
          - icon: fab fa-github
            url: https://github.com/retalOne/retalone.github.io
          - icon: fab fa-twitter
            url: https://twitter.com/OneRetal

      - title: Conversion machines Hyper-V vers ESXi
        content: Ce projet porte sur la conversion de machines au format VHDX vers le format VMDK.
        image: /images/projects/conversion.PNG
        #featured:
          #name: Demo
          #link: https://django-converter.herokuapp.com
        badges:
          - "HYPER-V"
          - "ESXI"
          - "QEMU-IMG"
        #links:
          #- icon: fab fa-github
            #url: https://github.com/gurusabarish/converter

      - title: Déploiement de la solution WAPT
        content: Ce projet porte sur le déploiement du logiciel WAPT et des logiciels installables via cette solution.
        image: /images/projects/wapt.png
        #featured:
          #name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "WAPT"
        #links:
          #- icon: fab fa-github
            #url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    title: "Me contacter!"
    content: Si vous avez des question, n'hésitez pas à m'envoyer un mail en cliquant sur le bouton ci-dessous!
    btnName: Envoyez moi un mail!
    btnLink: mailto:william.rascagneres70@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/RetalOne
      linkedin: https://linkedin.com
      twitter: https://twitter.com/OneRetal
      instagram: https://instagram.com/retaloneofficial
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Made By RetalOne's Corporation with HUGO"
    pageNotFound: "Vous avez trouvé... le néant. Il n'y a rien ici, pas encore."
    emailText: "Mon portfolio"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
